modLoader = "javafml"
loaderVersion = "${forgeLoaderVersion}"
license = "All Rights Reserved"

[[mods]]
modId = "tensura_iron_spell"
version = "${modVersion}"
displayName = "Tensura Compat: Iron's Spells n Spellbooks"

authors = "MinhEragon"
description = '''
A Compat mod between Tensura:Reincarnated & Iron's Spells n Spellbooks.
'''

[[dependencies.tensura_iron_spell]]
    modId = "forge"
    mandatory = true
    versionRange = "${forgeLoaderVersion}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.tensura_iron_spell]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraftVersionCheck}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.tensura_iron_spell]]
    modId="manascore"
    mandatory=true
    versionRange="${manasVersionCheck}"
    ordering="NONE"
    side="BOTH"