modLoader = "javafml"
loaderVersion = "${forgeLoaderVersion}"
license = "All Rights Reserved"

[[mods]]
modId = "tensura_iaf"
version = "${modVersion}"
displayName = "Tensura Compat: Ice and Fire"

authors = "MinhEragon"
description = '''
A Compat mod between Tensura:Reincarnated & Ice and Fire.
'''

[[dependencies.tensura_iaf]]
    modId = "forge"
    mandatory = true
    versionRange = "${forgeLoaderVersion}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.tensura_iaf]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraftVersionCheck}"
    ordering = "NONE"
    side = "BOTH"